name: Build, Test, Release
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt update && sudo apt install -y nasm qemu-utils gocr mkisofs dosfstools
      - name: Build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: images
          if-no-files-found: error
          path: |
            *.iso
            *.qcow2
            *.raw
            *.vdi
            *.vhd
            *.vmdk
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install testing tools
        run: sudo apt update && sudo apt install -y gocr qemu-utils qemu qemu-kvm gocr imagemagick
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: images
      - name: Run test
        run: ./test.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screendumps
          path: '*.png'
  release:
    needs: test
    name: Release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: images
      - name: Create release
        run: gh release create -d ${{ github.ref }} *.iso *.qcow2 *.raw *.vdi *.vhd *.vmdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
